layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: true
    forks: true
    projects:
     - zebra-test-page
     - python-memoize
     - nand2tetris
     - puzzles
     - tnschneider.github.io
     

social_media:
  linkedin: terry-schneider-281646b3
  stackoverflow: 7925985
  hackerrank: tnschneider
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: .NET Core
    web_url: https://dotnet.microsoft.com/
    image_url: https://upload.wikimedia.org/wikipedia/commons/e/ee/.NET_Core_Logo.svg

  - name: Xamarin
    web_url: https://dotnet.microsoft.com/apps/xamarin
    image_url: https://cdn.worldvectorlogo.com/logos/xamarin.svg

  - name: Vue
    web_url: https://vuejs.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg

  - name: Mongo DB
    web_url: https://www.mongodb.com/
    image_url: https://toppng.com/uploads/preview/mongo-db-design-mongodb-logo-mongodb-11562879783bwj2cknalk.png

  - name: Angular
    web_url: https://angular.io/
    image_url: https://angular.io/assets/images/logos/angularjs/AngularJS-Shield.svg

  - name: Flutter
    web_url: https://flutter.dev/
    image_url: https://cdn.worldvectorlogo.com/logos/flutter-logo.svg

  - name: OR-Tools
    web_url: https://developers.google.com/optimization
    image_url: https://i.imgur.com/9ZTrz8U.png